### ISSUE TITLE
Bug when using `density=True` with `chunks_to_segments=True`

### ISSUE THREAD

**Issue by dougiesquire** [xgcm/xrft#102]
I think there is a bug when using `density=True` with `chunks_to_segments=True`. This can be demonstrated by testing Parseval's theorem for the case of chunked arrays. 

For an unchunked array, the integral of the psd matches the variance:
```python
import numpy as np
import xarray as xr
from xrft.xrft import power_spectrum

data = xr.DataArray(np.random.normal(0, 1, size=1000), 
                    dims=['t'], 
                    coords=[range(0,1000)])

psd = power_spectrum(data, dim=['t'])

print(f"Integral of psd: {psd.integrate('freq_t').values}")
print(f"Variance: {(data.std()**2).values}")
```
```
Integral of psd: 0.9578122989216458
Variance: 0.9577984563349068
```

However, if we chunk the array into more than one chunk, the integrals of the psd for each segment do not match the corresponding variances:
```python
data_chunked = data.chunk({'t': 500})

psd = power_spectrum(data_chunked, dim=['t'], 
                     chunks_to_segments=True)

print(f"Integral of psd: {psd.integrate('freq_t').values}")
print(f"Variance: {[(data[:500].std()**2).item(), (data[500:].std()**2).item()]}")
```
```
Integral of psd: [0.2404514 0.2382441]
Variance: [0.958114994451872, 0.9466505378063875]
```

This is because the `N` used in the normalisation with `density=True` is computed from the dimension sizes of the input array rather than from the chunk sizes (so in the example above, the powers are off by a factor of (1000/500)**2 = 4).

**Comment by rabernat** [comment]
Hi Dougie! Thanks so much for this clear bug report.

I agree with your characterization of the bug. We would welcome a pull request to fix this. Is that something you would be interested in taking on?

**Comment by dougiesquire** [comment]
Sure - I could have a stab

**Comment by dougiesquire** [comment]
Ready for review @rabernat
