### ISSUE TITLE
Correction for reduced energy when windowing

### ISSUE THREAD

**Issue by dougiesquire** [xgcm/xrft#104]
Applying window weighting (e.g. Hann) to a signal reduces its energy. I think it's common to want to correct for this. For example, it appears that such a correction is applied by default in `scipy.signal.welch`:

```python
import xrft
import numpy as np
import scipy.signal
import xarray as xr
import matplotlib.pyplot as plt 

x = xr.DataArray(np.random.normal(0, 1, size=10000), 
                 dims=['t'], 
                 coords=[range(0,10000)])
n_segment = 100

f_scipy, p_scipy = scipy.signal.welch(x.values,
                                      window='hann',
                                      nperseg=n_segment,
                                      noverlap=0,
                                      return_onesided=False)
                
p_xrft = xrft.xrft.power_spectrum(x.chunk({'t': n_segment}), 
                                  dim=['t'],
                                  detrend='constant',
                                  window=True,
                                  chunks_to_segments=True).mean('t_segment')

# Correction tends to 8/3 for infinitely long Hann window
p_xrft_corrected = (1 / np.mean(np.hanning(n_segment)**2))*p_xrft 

plt.plot(f_scipy, p_scipy, 
         label='scipy psd')
plt.plot(p_xrft.freq_t, p_xrft, 
         color='C2', label='xrft psd')
plt.plot(p_xrft.freq_t, p_xrft_corrected, 
         linestyle='--', color='C1', label='corrected xrft psd')
plt.ylim(0,1.6)
plt.xlabel('freq')
plt.ylabel('psd')
plt.legend()
```
![delete-2](https://user-images.githubusercontent.com/42455466/91297889-6ddc4a00-e7e2-11ea-95a8-28a3dfb8e2de.png)

Is there an appetite (beyond my own) to have an option to apply such a correction when using `window=True` in `xrft`?

**Comment by navidcy** [comment]
Was this fixed or should it be still an open issue?

**Comment by roxyboy** [comment]
No, do you want to start a PR @navidcy ?

**Comment by navidcy** [comment]
I might but perhaps next week ;)

**Comment by roxyboy** [comment]
@dougiesquire I haven't been able to satisfy the Parseval's equation when I apply the correction you've suggested, i.e. `p_xrft_corrected.mean('freq_t) = ((x_stacked - x_stacked.mean(['t']))**2).mean(['t_segment']).mean('t)` where `x_stacked` is `x` stacked into n_segment chunks. Have you been able to sort this out?

**Comment by roxyboy** [comment]
Perhaps this has to do with the window (and data) not being indefinitely long but I would prefer to prioritize the Parseval's identity over this amplitude correction.

**Comment by dougiesquire** [comment]
> @dougiesquire I haven't been able to satisfy the Parseval's equation when I apply the correction you've suggested, i.e. `p_xrft_corrected.mean('freq_t) = ((x_stacked - x_stacked.mean(['t']))**2).mean(['t_segment']).mean('t')` where `x_stacked` is `x` stacked into `n_segment` chunks. Have you been able to sort this out?

Is it close? I suspect this has to do with what exactly you are checking. Can you point me at your test function?

**Comment by roxyboy** [comment]
> Is it close? I suspect this has to do with what exactly you are checking. Can you point me at your test function?

I tagged in PR #136 .

**Comment by roxyboy** [comment]
```
N = 10000
x = xr.DataArray(np.random.normal(0, 1, size=N), 
                 dims=['t'], 
                 coords=[range(0,N)])
dt = x.t.diff('t')[0]
n_segment = 100
x_stacked = _stack_chunks(x.chunk({'t':n_segment}), ['t'])
windows, x_windowed = _apply_window(x_stacked, ['t'])
f_scipy, p_scipy = sps.welch(x.values,
                             window='hann',
                             nperseg=n_segment,
                             noverlap=0,
                             return_onesided=False)
                
p_xrft = xrft.xrft.power_spectrum(x.chunk({'t':n_segment}), 
                                  dim=['t'],
                                  detrend='constant',
                                  window=True,
                                  chunks_to_segments=True).mean('t_segment')


for i in range(len(windows)):
    p_xrft_corrected = p_xrft / (windows[i]**2).mean()

xvar = ((x_stacked - x_stacked.mean(['t']))**2).mean(['t_segment'])

print(xvar.mean('t').compute(), np.mean(p_scipy), p_xrft_corrected.mean('freq_t').compute())
<xarray.DataArray 'reshape-8d476adf68eeec4f55cd26b30c57030f' ()>
array(0.99181735) 0.9854645032146411 <xarray.DataArray ()>
array(0.98500136)
```

Here's a re-produceable example.

**Comment by dougiesquire** [comment]
Are you sure `_apply_window()` is the same as in `xrft.xrft`? I get the following when trying to run your code. I'm probably doing something stupid...
<img width="610" alt="Screen Shot 2021-02-07 at 9 26 54 am" src="https://user-images.githubusercontent.com/42455466/107130965-b158e980-6926-11eb-99af-2f5b24062a26.png">

**Comment by roxyboy** [comment]
Sorry, I forgot to mention that I changed the `_apply_window` function to also return the windows as below:

```
def _apply_window(da, dims, window_type="hanning"):
    """Creating windows in dimensions dims."""

    if window_type not in ["hanning"]:
        raise NotImplementedError("Only hanning window is supported for now.")

    numpy_win_func = getattr(np, window_type)

    if da.chunks:

        def dask_win_func(n):
            return dsar.from_delayed(delayed(numpy_win_func, pure=True)(n), (n,), float)

        win_func = dask_win_func
    else:
        win_func = numpy_win_func

    windows = [
        xr.DataArray(win_func(len(da[d])), dims=da[d].dims, coords=da[d].coords)
        for d in dims
    ]

    return windows, da * reduce(operator.mul, windows[::-1])
```

**Comment by dougiesquire** [comment]
Sorry, I'm now not quite sure what the issue is here. It looks like with the correction we agree well with `sps.welch` (although I'm still not sure why they don't match exactly). Is your issue with the discrepancy between `xvar.mean('t')` and `np.mean(p_scipy)` /  `p_xrft_corrected.mean('freq_t')`?

**Comment by roxyboy** [comment]
> Is your issue with the discrepancy between `xvar.mean('t')` and `np.mean(p_scipy)` / `p_xrft_corrected.mean('freq_t')`?

Yes, because this means that the Parseval's identity is no longer satisfied for the "corrected" spectrum.

**Comment by dougiesquire** [comment]
It is approximately satisfied. Without the correction in the above example, `p_xrft.mean('freq_t')` will be somewhere around 0.36, which is totally off. I'm still thinking about exactly why the discrepancy between `xvar.mean('t')` and `p_xrft_corrected.mean('freq_t')` is larger for multiple `n_segment`s. But our correction matches `sps.welch` which is good I suppose...

**Comment by dougiesquire** [comment]
The slight difference between our corrected results and scipy's comes from a difference in the way the window is defined:
`scipy` uses the `scipy.windows` module with `sym=False`, which produces for example:
```python
>>> sps.windows.hann(5, sym=False)
array([0.       , 0.3454915, 0.9045085, 0.9045085, 0.3454915])
```

whereas we use `numpy.hanning`, which gives:
```python
>>> np.hanning(5)
array([0. , 0.5, 1. , 0.5, 0. ])
```
If you pass `window='windows[0]'` to `sps.welch()` rather than `window='hann'`, then you'll get exactly the same values as our corrected results. Perhaps it would be a good idea for `xrft` to also use `scipy.windows`? This would make extending to other windows very easy.

Regarding satisfying Parseval's _exactly_ with finite-length, non-uniform windowing, I'm not actually sure this is possible to do generally with a simple correction to the psd. I'm not sure of the best way to deal with this in our tests. Perhaps instead of `npt.assert_almost_equal()` on the values of the energy, we could check that the percentage difference is small? Although, I doubt this will be very robust.

I still think it's worthwhile having this correction available (ideally default) as I'd rather have spectra that approximately satisfy Parseval's and are consistent with `scipy` than spectra that don't and aren't.

**Comment by roxyboy** [comment]
> If you pass `window='windows[0]'` to `sps.welch()` rather than `window='hann'`, then you'll get exactly the same values as our corrected results. Perhaps it would be a good idea for `xrft` to also use `scipy.windows`? This would make extending to other windows very easy.

I agree with this.
