### ISSUE TITLE
release workflow failed due to incorrect secrets

### ISSUE THREAD

**Issue by rabernat** [xgcm/xrft#106]
In #101, we added a workflow to automatically upload a release to pypi. It failed due to credentials issues. I will resolve this by double checking our secrets.

https://github.com/xgcm/xrft/runs/1096581077?check_suite_focus=true

**Comment by rabernat** [comment]
Ok, the problem is that @roxyboy is the sole maintainer on pypi: https://pypi.org/project/xrft/

Takaya, can you add me as a maintainer. My credentials are associated with the xgcm organization-level secrets.

**Comment by rabernat** [comment]
@roxyboy, could you add me as a maintainer for xrft on pypi? Thanks

**Comment by roxyboy** [comment]
@rabernat I tried inviting you as a maintainer. Did it work??

**Comment by rabernat** [comment]
Yes, and the workflow ran! 0.2.1 is released! 🎉

**Comment by roxyboy** [comment]
Amazzzzing!!!
