### ISSUE TITLE
Code formatting? Perhaps black to match xgcm

### ISSUE THREAD

**Issue by navidcy** [xgcm/xrft#115]
I'm suggesting here something similar to https://github.com/xgcm/xgcm/pull/131

**Comment by rabernat** [comment]
Definitely needed!

@jbusecke recently polished up all of the CI for xgcm. Maybe he can do some of the same for xrft? Julius, do you use xrft? It's very important to those of us who do spectral stuff.

**Comment by jbusecke** [comment]
Nope have not used it, but I can format it for sure!

**Comment by jbusecke** [comment]
Should I wait for #112 before starting this? I think it will make all the diffs a mess.

**Comment by navidcy** [comment]
#112 is merged ;)
