### ISSUE TITLE
Release v0.3.0?

### ISSUE THREAD

**Issue by navidcy** [xgcm/xrft#131]
There are quite some bug fixes/changes [since 0.2.3](https://github.com/xgcm/xrft/compare/v0.2.3...master). I think some of the changes were breaking ones (correct me if I'm wrong) and, therefore, v0.3.0 is appropriate?

**Comment by rabernat** [comment]
I agree! But let's get #129 in first.

I don't think we have any breaking changes. We should avoid those at all costs. But we do have major new features, so 0.3.0 is right.

**Comment by rabernat** [comment]
Given the recent discussion, I think we need a documentation update (#86) before we can do another release. A lot has changed with #129 that we need to explain to users.

**Comment by roxyboy** [comment]
I'm personally keen on releasing version 0.3 as soon as we can merge PR #140 . The readthedocs is compiling now locally so I'd appreciate any feedback. You can compile the documentation via `make html` using [Sphinx](https://www.sphinx-doc.org/en/master/usage/quickstart.html).

**Comment by rabernat** [comment]
I think we are ready to release. @roxyboy would you like to do the honors. Just go to https://github.com/xgcm/xrft/releases/new. The string to use for the release tag is `v0.3.0`.

**Comment by roxyboy** [comment]
Great, I'd be happy to :)

**Comment by roxyboy** [comment]
Done 👍
