### ISSUE TITLE
How to do 'idft'

### ISSUE THREAD

**Issue by liu-ran** [xgcm/xrft#138]
Hi, I read the manual and found there exists the function `xrft.ifdt`. But it can't be used as the picture shows:

 
![微信图片_20210215213200](https://user-images.githubusercontent.com/48266323/107952900-55046280-6fd5-11eb-822c-0a36175206e7.png)

**Comment by roxyboy** [comment]
Until PR #136 is merged and new version for pip and conda is released, you'd have to install `xrft` via `git clone` and `python setup.py install` in order to have the `idft` functionality available. We're working on a new release so it should be available soon from pip or conda.

**Comment by liu-ran** [comment]
Thanks! @roxyboy
