### ISSUE TITLE
Isotropize returns unexpected range of wavenumbers

### ISSUE THREAD

**Issue by wenegrat** [xgcm/xrft#145]
Thanks for working on this project, it seems like it will be very useful. 

I wanted to flag what seems to me to be unexpected behavior from isotropize.

Specifically the calculation of a radial wavenumber as, 

>     freq_r = np.sqrt(k ** 2 + l ** 2).rename("freq_r")

gives a vector where the highest wavenumber exceeds the Nyquist wavenumber. For example if the sample spacing is 1,  this gives a maximum wavenumber of 0.7. This is because the isotropic spectrum is being calculated out into the corner of the Cartesian grid, for instance outside the black line in the following plot:

![download-2](https://user-images.githubusercontent.com/6423335/113357216-9ea0d680-9311-11eb-8185-85decab3aee1.png)

This to me seems like undesirable behavior, and for instance it can result in a rapid roll of energy above the k, l Nyquist frequency (as higher than this you only have energy from wavenumbers oriented towards the corners of the Cartesian grid.

I would think the expected behavior would follow that from calc_ispec in @cesar-rocha's package [pyspec](https://github.com/pyspec/pyspec), which I reproduce below to show the difference.

> def calc_ispec(k,l,E,ndim=2):
    """ Calculates the azimuthally-averaged spectrum
        Parameters
        ===========
        - E is the two-dimensional spectrum
        - k is the wavenumber is the x-direction
        - l is the wavenumber in the y-direction
        Output
        ==========
        - kr: the radial wavenumber
        - Er: the azimuthally-averaged spectrum """

    dk = np.abs(k[2]-k[1])
    dl = np.abs(l[2]-l[1])

    k, l = np.meshgrid(k,l)

    wv = np.sqrt(k**2+l**2)

    if k.max()>l.max():
        kmax = l.max()
    else:
        kmax = k.max()

    if ndim==3:
        nl, nk, nomg = E.shape
    elif ndim==2:
        nomg = 1

    dkr = np.sqrt(dk**2 + dl**2)
    kr =  np.arange(dkr/2.,kmax+dkr/2.,dkr)
    Er = np.zeros((kr.size,nomg))

    for i in range(kr.size):

        fkr =  (wv>=kr[i]-dkr/2) & (wv<=kr[i]+dkr/2)
        dth = np.pi / (fkr.sum()-1)
        if ndim==2:
            Er[i] = (E[fkr]*(wv[fkr]*dth)).sum()
        elif ndim==3:
            Er[i] = (E[fkr]*(wv[fkr]*dth)).sum(axis=(0,1))

    return kr, Er.squeeze()

Note that here wv is equivalent to freq_r, but is used only defining the radius at which the azimuthal integration is performed (and again only out to the maximum wavenumber in k,l), and is not the same as the returned isotropic frequencies 'kr'. 

I haven't tested, but my assumption is that freq_r gives the correct radial wavenumbers, aside from the above behavior I am flagging of extending out to the corners, such that a user could just truncate their spectra at the appropriate k or l Nyquist wavenumber. Is this correct?

If so, I'd suggest perhaps either truncating the returned vector using a logic similar to the code snippet above, or at least documenting this behavior clearly (for instance there is no truncation used in the MITgcm example, which suggests the highest wavenumbers are not sensible).

**Comment by rabernat** [comment]
👋  @wenegrat! Welcome to xrft!

I personally am 💯  👍  on truncating the isotropic wavenumber range to within this radius. It has never made sense to me to include those corner regions. But I'm curious what the other devs (particularly @roxyboy) think about this.

**Comment by roxyboy** [comment]
Truncating the wavenumbers sounds like a reasonable idea. I can work on it.

**Comment by rabernat** [comment]
> I can work on it.

Why not invite @wenegrat to implement it instead? It looks like he has already dug into the code. Always good to have more contributors to the package! 😊 

Would we want to do this via a deprecation cycle? If we just change something like this suddenly, it could break code that relies on the current behavior.

**Comment by roxyboy** [comment]
> Why not invite @wenegrat to implement it instead? It looks like he has already dug into the code. Always good to have more contributors to the package! 😊
> 
> Would we want to do this via a deprecation cycle? If we just change something like this suddenly, it could break code that relies on the current behavior.

If @wenegrat can make a PR, I'd be more than happy to have his input. Since it's a truncation of the wavenumber without any changes to the flags or coordinate names, I don't think it would cause a breaking in the code but... perhaps it's safer to have a cycle...?

**Comment by rabernat** [comment]
> Since it's a truncation of the wavenumber without any changes to the flags or coordinate names, I don't think it would cause a breaking in the code

Imagine, for example, that someone is using xrft as part of an automated system that runs every night. They are aware of this issue and are applying truncation of the spectrum using `isel`. Now we release a new version of xrft that does this truncation internally and it gets updated on their system. Their code would now be wrong. It wouldn't necessarily error--it would just give wrong results.

I think the polite thing to do is at least add a warning to all isotropic functions (which we can remove after two releases).

**Comment by roxyboy** [comment]
> Imagine, for example, that someone is using xrft as part of an automated system that runs every night. They are aware of this issue and are applying truncation of the spectrum using `isel`. Now we release a new version of xrft that does this truncation internally and it gets updated on their system. Their code would now be wrong. It wouldn't necessarily error--it would just give wrong results.
> 
> I think the polite thing to do is at least add a warning to all isotropic functions (which we can remove after two releases).

Makes sense. Let's go for a deprecation cycle :)

**Comment by wenegrat** [comment]
Sure I’ll take a shot at it.

**Comment by rabernat** [comment]
Jacob, would you be interested in implementing this change yourself? We would be very happy to walk you through the contribution process.

**Comment by rabernat** [comment]
> Sure I’ll take a shot at it.

Great! The [developer docs](https://xrft.readthedocs.io/en/latest/contributor_guide.html) can help you get started. And feel free to ask any questions, no matter how simple.

If I had to guess, I would say to start with this part of the code:

https://github.com/xgcm/xrft/blob/2bb85b3e532b1cd9ff89409b499d16798377da15/xrft/xrft.py#L985-L986

You will want to define `kr` differently.

**Comment by roxyboy** [comment]
@wenegrat Could you take a look at PR #152 and see if it looks ok?

**Comment by wenegrat** [comment]
@roxyboy apologies for not getting to this, it's been sitting on my to-do list making me feel guilty. 

I think your implementation looks good. Thanks again.

**Comment by roxyboy** [comment]
PR #152 fixed this so I'm going to close this :)
