### ISSUE TITLE
Erroneous examples in documentation

### ISSUE THREAD

**Issue by lanougue** [xgcm/xrft#147]
Hello everybody,
I wasn't aware of the new realase ! I just had a look. Thanks all for the excellent job!
I gave a look in the doc at "example of discrete and inverse discrete Fourier transform" and recognized my favorite example ;) However I found something a bit erroneous. In cell [13] of the notebook, the numpy fft (npft) has to be 1) "fftshifted", 2) multiplied by the "r" factor and 3) multiplied by "dx" before plotting in order to look-like the theoretical transform.
I can understand about the "dx" for the amplitude, however the "r" factor (and the fftshift)  is a pure fancyful factor I had some hard time to remove in dft. I think this example totaly minimize the phase impact in fft and mislead the reader since what is plotted is not really the numpy (or xrft) fft output.

To clarify as much as possible the documentation, I think this example should exactly point the difference between xrft.fft, xrft.dft and numpy.fft

I think the forward (dft and fft) and backward transformation (idft and ifft) desesrves a decicated different example documentation.

I can help for this if needed

**Comment by rabernat** [comment]
Hi @lanougue! Thanks a lot for checking this.

We would really appreciate your contributions to the documentation. Since you led the implementation of the "shift" features, it makes sense for you to be the one to update the documentation here. Feel free to propose whatever changes you think are needed via PR.

**Comment by lanougue** [comment]
Hi @rabernat. Yes, I will work on it. 

In the future,iIt would be nice if I could receive an email/notification when someone post an issue in xrft. Is there any list to subscribe to ?

**Comment by roxyboy** [comment]
PR #151 addressed this so I'm going to close this :)
