### ISSUE TITLE
Erroneous behaviour when coordinates of transformation is in decreasing order

### ISSUE THREAD

**Issue by lanougue** [xgcm/xrft#148]
Hi, looking to #144 issue, here is a "bug" behaviour:
```
T = xr.tutorial.open_dataset("air_temperature").air.isel(time=[0, 1])
T_f1 = xrft.dft(T, dim="lat", true_phase=True, true_amplitude=True)
T = T.sortby('lat')
T_f2 = xrft.dft(T, dim="lat", true_phase=True, true_amplitude=True)
```

T_f1 and T_f2 should be the same but are not.

**Comment by lanougue** [comment]
@roxyboy, @rabernat 
After a rapid check, as it is coded now, dft (and idft) can work correctly only if input data has increasing coordinates along the axis the dft is taken along. dft and idft need to be updated to take care of reversed coordinates.

From a performance point of view, I think that sorting can be slow (xr.DataArray.sortby) and only a "flip" is actually needed on the data since constant spacing is checked anyway. Actually fliping the data could probably be avoided by just creating a view before taking the actual fourier transform.

If we go like this, the _lag_coord() function has to be updated too.
What do you guys think ?
I can open a PR for that

**Comment by roxyboy** [comment]
A PR would be great, thanks @lanougue ! :)

**Comment by lanougue** [comment]
Done in #149 :)

**Comment by lanougue** [comment]
Done in #149 :)
