### ISSUE TITLE
'isotropize' function fail to work

### ISSUE THREAD

**Issue by liu-ran** [xgcm/xrft#153]
![微信图片_20210531162437](https://user-images.githubusercontent.com/48266323/120192138-65bbaa00-c24d-11eb-81d3-a86cd80444ee.png)

**Comment by roxyboy** [comment]
Can you tell me what `xarray` and `dask` version you're using?

**Comment by liu-ran** [comment]
@roxyboy Hi, 'xarray' version is 0.15.1  and the 'dask' is  2.25.0

**Comment by roxyboy** [comment]
Can you try updating your xarray and see if that'll solve the issue (the latest version is 0.18)? I'm using xarray=0.16.2 and that doesn't seem to have an issue with `isotropic_power_spectrum`.

**Comment by roxyboy** [comment]
Looping in issue #150 , maybe we should have a soft requirement for the xarray version @rabernat ?? It seems we depend quite a lot on the cutting edge development of xarray and dask.

**Comment by liu-ran** [comment]
@roxyboy  0.16.2 is very good. Thank you!

**Comment by rabernat** [comment]
> Looping in issue #150 , maybe we should have a soft requirement for the xarray version @rabernat ?? It seems we depend quite a lot on the cutting edge development of xarray and dask.

We should determine what version of xarray is required for xrft to work and then fix that in our package requirements definition (e.g. requirements.txt). I would not characterize Xarray 0.16.2 as a cutting edge version.
