### ISSUE TITLE
Padding error: Deal with dimension with odd number

### ISSUE THREAD

**Issue by LL-Geo** [xgcm/xrft#172]
The pad function show error when the original coordinate dimension has an odd number.

---------------------------------------------------------------------------
Oringal data
xarray.DataArray'magnetic_anomaly'northing: 131 easting: 80

---------------------------------------------------------------------------

✔️ da_padded = xrft.pad(Input,easting=24,northing=24)
     xarray.DataArray'magnetic_anomaly'northing: 179 easting: 128

---------------------------------------------------------------------------

❌ da_padded = xrft.pad(Input,easting=24,northing=21)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_12080/945327050.py in <module>
      2 npd=21
      3 
----> 4 da_padded = xrft.pad(Input,easting=epd,northing=npd)
      5 da_padded

~\Anaconda3\envs\fati\lib\site-packages\xrft\padding.py in pad(da, pad_width, mode, stat_length, constant_values, end_values, reflect_type, **pad_width_kwargs)
    166     )
    167     # Pad the coordinates selected in pad_width
--> 168     padded_coords = _pad_coordinates(da.coords, pad_width)
    169     # Assign the padded coordinates to the padded array
    170     padded_da = padded_da.assign_coords(padded_coords)

~\Anaconda3\envs\fati\lib\site-packages\xrft\padding.py in _pad_coordinates(coords, pad_width)
    229         spacing = get_spacing(padded_coords[dim])
    230         # Pad the coordinates using numpy.pad with the _pad_coordinates callback
--> 231         padded_coords[dim] = np.pad(
    232             padded_coords[dim],
    233             pad_width=pad_width[dim],

<__array_function__ internals> in pad(*args, **kwargs)

~\Anaconda3\envs\fati\lib\site-packages\numpy\lib\arraypad.py in pad(array, pad_width, mode, **kwargs)
    762             inds = (ind + (Ellipsis,) for ind in inds)
    763             for ind in inds:
--> 764                 function(view[ind], pad_width[axis], axis, kwargs)
    765 
    766         return padded

~\Anaconda3\envs\fati\lib\site-packages\xrft\padding.py in _pad_coordinates_callback(vector, iaxis_pad_width, iaxis, kwargs)
    274     vmin, vmax = vector[n_start], vector[-(n_end + 1)]
    275     vector[:n_start] = np.arange(vmin - spacing * n_start, vmin, spacing)
--> 276     vector[-n_end:] = np.arange(vmax + spacing, vmax + spacing * (n_end + 1), spacing)
    277     return vector
    278 

ValueError: could not broadcast input array from shape (22,) into shape (21,)

**Comment by santisoler** [comment]
Thanks @LL-Geo for opening this issue. Here I copy a simple working example that reproduces this bug:

```python
import numpy as np
import xarray as xr
import xrft


easting = np.linspace(0, 6, 7)
northing = np.linspace(-4, 4, 13)
dummy_data = np.ones((northing.size, easting.size))
data = xr.DataArray(
    dummy_data,
    coords={"easting": easting, "northing": northing},
    dims=("northing", "easting"),
)

pad_data = xrft.pad(data, easting=2, northing=3)
```

```
Traceback (most recent call last):
  File "reproduce_bug.py", line 15, in <module>
    pad_data = xrft.pad(data, easting=2, northing=3)
  File "/home/santi/git/xrft/xrft/padding.py", line 168, in pad
    padded_coords = _pad_coordinates(da.coords, pad_width)
  File "/home/santi/git/xrft/xrft/padding.py", line 231, in _pad_coordinates
    padded_coords[dim] = np.pad(
  File "<__array_function__ internals>", line 180, in pad
  File "/home/santi/.mambaforge/envs/test_env_xrft/lib/python3.8/site-packages/numpy/lib/arraypad.py", line 764, in pad
    function(view[ind], pad_width[axis], axis, kwargs)
  File "/home/santi/git/xrft/xrft/padding.py", line 275, in _pad_coordinates_callback
    vector[:n_start] = np.arange(vmin - spacing * n_start, vmin, spacing)
ValueError: could not broadcast input array from shape (4,) into shape (3,)
```

I suspect the reason behind it is that I unwisely chose `np.arange` for building the extended padded coordinates, while `np.linspace` is a much safe option. Apparently `np.arange` is generating an array with an extra element so I cannot be used to replace the values of the original `vector` variable. I'll open a PR to solve this bug plus some tests that checks that we won't deal with this bug in the future.

**Comment by roxyboy** [comment]
PR #180  fixed this.
