### ISSUE TITLE
Usage of `fft real_dim`

### ISSUE THREAD

**Issue by KevinYanesG** [xgcm/xrft#178]
Hi, awesome library! I have one question:

If I understood correctly from https://github.com/xgcm/xrft/blob/master/xrft/xrft.py#L377, when we specify a `real_dim` it should call `fftm.rfftn` from the `fftm_module`. Although, when I look into the [definition](https://github.com/xgcm/xrft/blob/42abb0fd0474f891cab84e0ede86d7f18c16b8b4/xrft/xrft.py#L37) of the `_fft_module`, the `rfftn` doesn't exist. I was expecting a call to `numpy.rfft()` here. Am I missing something? Why there are no errors thrown if  `fftm.rfftn` doesn't exist? Are we using the performance advantage of `np.rfft` over `np.fft`?

Thanks in advance!

**Comment by roxyboy** [comment]
Hi @KevinYanesG, thanks for raising an issue. The reason why `numpy.rfft` doesn't exist in `_fft_module` is because we are calling the entire fft module, under which rfft exists, i.e. `numpy.fft.rfft()`.

**Comment by KevinYanesG** [comment]
Aaah! You are calling the module `np.fft` and not the method `np.fft.fft`, now I see it! Many thanks @roxyboy !
