### ISSUE TITLE
handling error when coordinates are not numerical

### ISSUE THREAD

**Issue by lanougue** [xgcm/xrft#188]
Hello,

I tried to apply fft on an xarray whose one of coordinates are not numerical (string in my case). The returned error is not explicit:
````
TypeError: unsupported operand type(s) for -: 'str' and 'str'
````
I think that an explicit error should be raised when the coordinate is not numerical.

**Comment by roxyboy** [comment]
Hi @lanougue , I support this idea. Would you mind making a PR?

**Comment by lanougue** [comment]
Hi @roxyboy , Ok, I will try to do a PR when I'll find some spare time !

**Comment by lanougue** [comment]
Opening PR #190
