### ISSUE TITLE
dim or dims 

### ISSUE THREAD

**Issue by lanougue** [xgcm/xrft#194]
The correct keyword when calling xrft functions is "dim". However, I frequently use dims which do not raise an error but may result in unexpected results depending on the provided xarray to transform (dims is added to kwargs silently).
Shouldn't we accept both dim and dims to avoid these kind of things or raise an error/warning to warn the user that he used dims instead of dim ?

**Comment by roxyboy** [comment]
We've avoided using `dims` as an input argument for `xrft` as we didn't want to conflict with the `dims` used in `xarray.DataArray`s.

**Comment by roxyboy** [comment]
I think I take back my previous argument. I'm fine with changing the code to accept both `dim` and `dims` as inputs and eventually unifying them to `dims`.

**Comment by lanougue** [comment]
Nice !
I'll try a PR in the coming weeks

**Comment by cgahr** [comment]
In my opinion, it should be either, not both. I think the correct choice is `dim`, the xarray docs seem to imply that `dims` is only used if there are multiple dimensions (see `xr.dot`) while `dim` seems to mean `dimension[s]` (compare to `xr.mean`). 

In case of the fourier transform, we can always only choose one dimension, so `dim` seems to be correct.
