### ISSUE TITLE
mfdataset and chunks

### ISSUE THREAD

**Issue by dcherian** [xgcm/xrft#24]
I'm using `xarray.mfdataset` to open SST files stored as 1 timestep per `.nc` file; so there is one chunk per file.

Using `xrft` to calculate the psd along time axis of `sst.sel(lon=90,lat=12)` (for example) throws an error because `dask.fft` can do an fft only along an axis that has one chunk in total. 

What is the expected usage here?

**Comment by rabernat** [comment]
Deepak! I'm happy you've found this package...I didn't know if anyone was actually using it! ;)

The solution is the following:
* If you can afford to load the dataset in memory, just call `.load()` before calling xrft
* If not, call `.chunk()` ([docs](http://xarray.pydata.org/en/stable/generated/xarray.Dataset.chunk.html?highlight=chunk)) to rechunk the data before calling xrft

If you post a more verbose example, I can be more specific.

**Comment by dcherian** [comment]
The package is super useful!

`.chunk()` seems to work but now Linux kills the process because it consumes too much memory (the whole dataset is only 3 gigs; and each file is only 8.5MB).

**Comment by rabernat** [comment]
If you have more than 3 GB of memory on the machine, just call `.load()`.

You probably want to call `.chunk()` with arguments, i.e. the new chunk sizes. The idea is to rechunk along dimensions that are not part of the Fourier transform. If you post more details (like a link to a notebook with your actual analysis), I could give more specific advice.
