### ISSUE TITLE
PyPI/conda package

### ISSUE THREAD

**Issue by kynan** [xgcm/xrft#5]
@rabernat, are you planning to package this for PyPI and/or conda?

/cc @alexamici

**Comment by rabernat** [comment]
Yes definitely! We have not actually made an official release yet. But knowing there is interest from the community will motivate us.

**Comment by kynan** [comment]
I've just packaged it for conda-forge: conda-forge/staged-recipes#3017

Want me to add you as a maintainer?

**Comment by rabernat** [comment]
Yes, thanks very much!

We really didn't think anyone else was using this package, but I'm glad to see that you have found it useful. Obviously there is lots more that could be added (e.g. #4). We would really welcome your involvement!

**Comment by kynan** [comment]
Sure, happy to be involved. Meanwhile, would you be happy to tag a release so we can point the recipe to a tag rather than master as pointed out by @jakirkham?

**Comment by rabernat** [comment]
Just tagged release v0.1
