### ISSUE TITLE
rotary spectrum

### ISSUE THREAD

**Issue by rabernat** [xgcm/xrft#50]
With velocity timeseries data, we often want to calculate the [rotary spectrum](https://journals.ametsoc.org/doi/pdf/10.1175/1520-0469%281979%29036%3C0757%3ASTSAOR%3E2.0.CO%3B2), i.e. the power spectrum of `u + iv`.  As in @anirban89's recent paper:
![image](https://user-images.githubusercontent.com/1197350/44696199-8e7f3700-aa44-11e8-9612-6352c0902134.png)

The main difference from a regular power spectrum is that, since the input is complex, we need to keep both positive and negative frequencies, which tell us about the sense of the rotation in the currents.

This would be straightforward to add to xrft.

**Comment by roxyboy** [comment]
I think `xrft.power_spectrum()` keeps both positive and negative frequencies in the output.
