### ISSUE TITLE
docs failing

### ISSUE THREAD

**Issue by rabernat** [xgcm/xrft#56]
https://readthedocs.org/projects/xrft/builds/8751504/

```
Solving environment: ...working... failed

ResolvePackageNotFound: 
  - sphinx=1.6.7
```

**Comment by roxyboy** [comment]
The docs are passing now but haven't been able to figure out how to automate updating the API page in readthedocs. I tried [`sphinxcontrib-apidoc`](https://pypi.org/project/sphinxcontrib-apidoc/) but it doesn't seem to do what I want...
