### ISSUE TITLE
Support real='coord'

### ISSUE THREAD

**Issue by dcherian** [xgcm/xrft#57]
Currently the `real` kwarg is boolean, and takes a real FFT along the last dimension. This means that the user needs to transpose the data to an appropriate shape. 

I propose that xrft support the following syntax:

`xrft.xrft.dft(da, dim=['time', 'longitude'], real='time')`

**Comment by roxyboy** [comment]
Thanks for pointing that out @dcherian. As of now, the `real` kwargs implements the `numpy.rfftn` function in paralyzation which only takes the real FFT along the last dimension: https://docs.scipy.org/doc/numpy/reference/generated/numpy.fft.rfftn.html#numpy.fft.rfftn

**Comment by dcherian** [comment]
I should've been clearer. 
`xrft.xrft.dft(da, dim=['time', 'longitude'], real='time')` should be equivalent to
`xrft.xrft.dft(da.transpose(['longitude', 'time']), dim=['time', 'longitude'], real=True)`

i.e. xrft does the appropriate transpose based on the `real` kwarg.

**Comment by roxyboy** [comment]
That makes sense for two dimensional arrays but for higher dimensional arrays, I'm not sure if the transposing should be made automatically...

We could either implement a warning when the `real` kwarg is used or automate the transposition.

**Comment by rabernat** [comment]
@dcherian, we really appreciate your feedback on this. There are not many people working on xrft...just me and @roxyboy (and I don't have much time for it these days).

We would be very happy to get a PR from you that addresses your issue. 😄

**Comment by rabernat** [comment]
Actually, @TomNicholas is the one who added the `real` option in #54, so maybe he would be a good person to address this.

**Comment by TomNicholas** [comment]
> I propose that xrft support the following syntax:
>
> `xrft.xrft.dft(da, dim=['time', 'longitude'], real='time')`

I think that API would be better than what I went for! Is there any performance/consistency reason why we shouldn't just transpose then apply `np.fft.rfftn`? If we're happy to transpose then this seems like a simple improvement to me?

> There are not many people working on xrft...just me and roxyboy (and I don't have much time for it these days).

At the risk of totally derailing the discussion.... Fourier transforms (and the xhistogram module I saw you started @rabernat) are so clearly generally-useful that I think we should push for these kind of tools to be packaged more centrally for the convenience of xarray's userbase. Not as part of xarray itself but more like the new scipy to xarray's numpy. Otherwise we're just going to end up with lots of xarray users reinventing the wheel over and over (which I think is already happening).

**Comment by dcherian** [comment]
>  Is there any performance/consistency reason why we shouldn't just transpose then apply np.fft.rfftn? If we're happy to transpose then this seems like a simple improvement to me?

If a user wants this feature, it's the only way to get it AFAIK without re-implementing `rfftn`. So yeah should be simple; transport; call `rfftn`; transpose back.

**Comment by roxyboy** [comment]
Ok, sounds good. Thanks for the feedback @TomNicholas and @dcherian. Would either of you be willing to submit a PR on this??

**Comment by rabernat** [comment]
> Not as part of xarray itself but more like the new scipy to xarray's numpy. Otherwise we're just going to end up with lots of xarray users reinventing the wheel over and over (which I think is already happening).

Agree. We have discussed this several times on xarray, e.g. here https://github.com/pydata/xarray/issues/1850

The main place for duplication seems to be https://github.com/fujiisoup/xr-scipy. They have discussed merging here:  https://github.com/fujiisoup/xr-scipy/issues/4

There is also https://github.com/crusaderky/xarray_extras,  https://github.com/smartass101/xarray-dsp, etc.

The main problem seems to be that we barely have enough xarray devs to maintain xarray itself. The effort required to merge these different packages is high.

**Comment by roxyboy** [comment]
Gave it a stab on PR #66. Would be great if I can have some feedback :)

**Comment by dcherian** [comment]
Thanks for your hard work, @roxyboy
