### ISSUE TITLE
xscale?

### ISSUE THREAD

**Issue by dcherian** [xgcm/xrft#72]
Just wanted to make sure that people knew of https://github.com/serazing/xscale

Seems like it's superset of xrft's functionality.

**Comment by rabernat** [comment]
Yes yes there are many similar packages out there. We could try to merge efforts with @serazing but there is a cost to that. For now, we use xrft and it works for us.

**Comment by roxyboy** [comment]
I'm not sure if this is an issue so I'm going to close it if there are suggestions otherwise...
