### ISSUE TITLE
dft dimension name

### ISSUE THREAD

**Issue by lanougue** [xgcm/xrft#76]
Hi everyone,

I got through a simple bug. When dimension along which I want to do a dft has more than one character, I got a ValueError.
Here is my simple code
`
a = xr.DataArray(np.arange(5), dims='xx')
xrft.dft(a, dim='xx')
`
I get the error: ValueError: 'x' not found in array dimensions ('xx',)

**Comment by roxyboy** [comment]
Can you try using the syntax: `xrft.dft(a, dim=['xx'])`? The dim argument is a list and not a string.

**Comment by lanougue** [comment]
When using name 'x', I don't have the error. When using the name 'xx' I have the error.
Using dim=['xx'] in xrft solves the problem.
However, this is quite disturbing...

**Comment by roxyboy** [comment]
I'm going to close this for now as it seems the issue is resolved. We kept the `dim` argument to take a list with foresight that taking DFT along multiple dimensions is often desired.

**Comment by rabernat** [comment]
I don't think this should be closed.

There is a problem with the way xrft parses these inputs. It expects a list, but doesn't raise an error if you provide a string. Internally it is just calling `dims[0]`, which in this case returns `x`.

We need to provide more robust input handling and better error messages. I would look into copying whatever xarray does. Xarray is able to smoothly handle `da.mean(dim='xx')` and `da.mean(dim=['xx'])`.

**Comment by roxyboy** [comment]
PR #80 should fix this issue. It allows the `dim` argument to take a string and not only a list of strings.

**Comment by lanougue** [comment]
Perfect ! Thanks !
