### ISSUE TITLE
Documentation should show how to satisfy parseval's theorem, and some other basics

### ISSUE THREAD

**Issue by dhruvbalwada** [xgcm/xrft#86]
Right now the documentation does not show how Parseval's theorem is satisfied by the output. This is something important to show because we often use it to do proper normalizations. Would be nice to have this somewhere in the documentation. Specially because most fft packages seem to not have any standard definitions, so it is important to show what definitions what your package is partaking in. 

Can also be useful to solve: #75

**Comment by roxyboy** [comment]
This is in the testing fwiw which we require it to pass every time a PR is made...

**Comment by dhruvbalwada** [comment]
Would still be nice to have. For example, it is not obvious to me how I might estimate the variance in different wavenumber ranges. Is the variance 

`1/L \int a^2 dx = \sum power_spectrum * spacing_freq`?

knowing the convention can help users.

**Comment by cspencerjones** [comment]
I agree! Just trying to get my head around this at the moment.

**Comment by roxyboy** [comment]
We can work on this as soon as the PR #129 is merged.

**Comment by dougiesquire** [comment]
Note #104 and #105 are also relevant to satisfying Parseval's Theorem

**Comment by rabernat** [comment]
So who is going to be writing this new documentation? 😉 

I'm happy to review once we have a draft started.

**Comment by roxyboy** [comment]
I opened a PR #135 for more documentation. Input would be welcomed :)

**Comment by roxyboy** [comment]
Closed via #140
