### ISSUE TITLE
isotropic_powerspectrum fails for extra dimensions

### ISSUE THREAD

**Issue by rabernat** [xgcm/xrft#9]
I think this is a self-contained minimum reproducible example of #6.

`isotropic_powerspectrum` doesn't work when there are extra dimensions.

```python
da = xr.DataArray(np.random.rand(5,20,30),
                  dims=['time', 'y', 'x'],
                  coords={'time': np.arange(5), 'y': np.arange(20), 'x': np.arange(30)})
xrft.isotropic_powerspectrum(da, dim=['y', 'x'])
```
error is
```
ValueError                                Traceback (most recent call last)
<ipython-input-24-6482ba3ce67d> in <module>()
----> 1 xrft.isotropic_powerspectrum(da, dim=['y', 'x'])

/Users/rpa/RND/Public/xrft/xrft/xrft.py in isotropic_powerspectrum(da, dim, shift, remove_mean, density, window, nbins)
    309     ps = power_spectrum(da, dim=dim, shift=shift,
    310                        remove_mean=remove_mean, density=density,
--> 311                        window=window)
    312     if len(ps.dims) > 2:
    313         raise ValueError('The data set has too many dimensions')

/Users/rpa/RND/Public/xrft/xrft/xrft.py in power_spectrum(da, dim, shift, remove_mean, density, window)
    185         ps /= (np.asarray(N).prod())**2
    186         for i in range(len(dim)):
--> 187             ps /= daft[coord[-i-1]].values
    188 
    189     return xr.DataArray(ps, coords=daft.coords, dims=daft.dims)

ValueError: operands could not be broadcast together with shapes (5,20,30) (5,) (5,20,30) 
```

Same thing happens for `isotropic_crossspectrum`

cc: @roxyboy

**Comment by roxyboy** [comment]
I think this issue is resolved unless the user tries to apply windowing to dask arrays.

**Comment by rabernat** [comment]
Do we have a test case for my example from my original comment?

**Comment by rabernat** [comment]
Now if I try this, I get the error

```python
ValueError: The data has too many or few dimensions. The input should only have the two dimensions to take the azimuthal averaging over.
```

Do we consider this closed?

**Comment by roxyboy** [comment]
I couldn't come up with a clean way to do it so yes, I coded it so that the user would have to use a `for` loop if the data has more than two dimensions.

**Comment by rabernat** [comment]
Ok, let's leave the issue open for now then.

**Comment by rabernat** [comment]
I just hit this issue again. It seems weird that we can't take isotropic spectra with more than 2 dimensions, provided that we are only doing FT in 2 of the dimensions.

**Comment by rabernat** [comment]
It basically comes down to bincount. Here is one possible solution:
https://stackoverflow.com/questions/40591754/vectorizing-numpy-bincount

The other possible solution would be to define a ufunc that does the azimuthal averaging and then call xarray.apply_ufunc. This would work well with dask, while the SO idea above would not.

**Comment by roxyboy** [comment]
It seems that the `numpy` community is "satisfied" with the user using a `for` loop for `np.bincount` with multi-dimensional arrays rather than adding a `axis` argument: https://github.com/numpy/numpy/pull/4330

I tried circumventing the issue by using `dask.array.map_blocks`, `xarray.apply_ufunc` and `numpy.apply_along_axis` but providing the `weights` argument for `np.bincount` seems to significantly complicate the syntax and couldn't get it to work.

**Comment by roxyboy** [comment]
@rabernat Kinda unsatisfying that I conceded to using a for loop but this [PR](https://github.com/xgcm/xrft/pull/70) allows `isotropic_powerspectrum` to take arrays with up to 4 dimensions.

**Comment by rabernat** [comment]
Wow numpy-groupies is amazing! Could be very useful in [xhistogram](https://xhistogram.readthedocs.io/en/latest/) as well!

**Comment by roxyboy** [comment]
PR #128 fixed this issue.
