### ISSUE TITLE
Getting Wavenumber Units Correct on Power Spectrum and Isotropic Spectrum

### ISSUE THREAD

**Issue by patrickcgray** [xgcm/xrft#92]
I've been working on a spatial power spectrum from HYCOM data and I'm not entirely sure I understand some of the wavenumber outputs. I assume that both the `power_spectrum` and `isotropic_power_spectrum` functions output wavenumbers as cycles per pixel (1/pix), and this I would just need to multiply this by pix/km to convert to cycles per kilometer, but this doesn't seem to produce reasonable wavenumbers for the output of either function, with the highest wavenumbers being ~1 cycle/km, higher than the resolution of the data which is 8km/pix. This also clearly isn't what is done in this example https://xrft.readthedocs.io/en/latest/MITgcm_example.html#Power-spectrum where the wavenumbers are multiplied by 1e3.

A fully functioning example of this can be seen here: https://colab.research.google.com/drive/19AMh-DtiBzkjoZJTUGklikiz4pHrVmux and you just need to upload the attached HYCOM netcdf file: [hycom_sst_2002.nc.zip](https://github.com/xgcm/xrft/files/4432629/hycom_sst_2002.nc.zip)

```
import numpy as np
import xarray as xr
import os.path as op
import xrft
from matplotlib import colors, ticker
import matplotlib.pyplot as plt
%matplotlib inline

hycom = xr.open_dataset('hycom_sst_2002.nc')

powerspec = xrft.power_spectrum(hycom.water_temp, dim=['lat', 'lon'], spacing_tol=0.01)
iso_powerspec = xrft.isotropic_powerspectrum(hycom.water_temp, dim=['lat', 'lon'],
                                  detrend='constant',window=False, nfactor=4, spacing_tol=0.01)

pix_per_km = 1/8

fig, axes = plt.subplots(nrows=3, ncols=1, figsize=(6,12))
fig.set_tight_layout(True)
hycom.water_temp.plot(ax=axes[0])
im = axes[1].pcolormesh(powerspec.freq_lon*pix_per_km, powerspec.freq_lat*pix_per_km, 
                        powerspec, norm=colors.LogNorm())
axes[2].plot(iso_powerspec.freq_r*pix_per_km, iso_powerspec)

# # just comparing to normal -5/3 line
x = iso_powerspec.freq_r*pix_per_km
y = np.power(iso_powerspec.freq_r, -5/3)
axes[2].plot(x, y)

cbar = fig.colorbar(im, ax=axes[1])
axes[2].set_xscale('log')
axes[2].set_yscale('log')
axes[1].set_xlabel(r'k [cpkm]')
axes[1].set_ylabel(r'l [cpkm]')
axes[2].set_xlabel(r'k$_r$ [cpkm]')
axes[2].set_ylabel(r'variance')
```
![spatial_spec_output](https://user-images.githubusercontent.com/2497349/78462747-fb3bc800-76a2-11ea-9b30-52023c66438b.png)

**Comment by roxyboy** [comment]
Since your metadata seems to be in lat-lon coordinates, the resulting coordinates of `xrft` will come out as cycles per lat-lon. If you want the output coordinates to be in cycles per km, you would need to change the input coordinates to km.

**Comment by roxyboy** [comment]
As for `isotropic_powerspectrum`, it internally calculates the wavenumber based on the given coordinate to isotropize a 2D spectrum so giving lat-lon coordinates to the function will result in the output having weird dimensions.

**Comment by patrickcgray** [comment]
Hi @roxyboy thanks for the response that totally makes sense. 

As a follow up in order to do what you've recommended, I see there is a lot of discussion on this and clearly many options, but do you know a recommended approach to going from lat/lon (WGS84/EPSG:4326) to a more appropriate CRS? Something like Lambert's Azimuthal Equal Area? After digging around a bit this doesn't seem to be possible in xarray but I'm curious if this can be done within the xarray ecosystem?

**Comment by roxyboy** [comment]
I've never used it myself but I've heard people rave about this: `https://github.com/JiaweiZhuang/xESMF`. You might want to check it out.
