### ISSUE TITLE
Variance increasing with increasing wavenumber

### ISSUE THREAD

**Issue by patrickcgray** [xgcm/xrft#94]
I'm getting a confusing result across a number of datasets and I wanted to see if this could be an issue or is an accurate representation of the data. I'm pulling MODIS data from OpenDap (I've also tried this with MODIS data from Google Earth Engine both as netcdfs and geotiffs and with both SST and chl-a) as shown in the code below and in all examples I'm getting negative variance at all wavenumbers and increasing variance at higher frequencies. When I take the absolute value it all looks correct but I shouldn't need to do that so I'm curious what I could be doing wrong or if this is a bug. The data looks relatively normal and as though it should have a normal cascade of variance down to smaller spatial scales (after taking absolute value it is roughly -5/3). As you can see here:

![image](https://user-images.githubusercontent.com/2497349/79510489-6ecac700-800b-11ea-9431-559437036ce9.png)

A full worked up example is here: https://colab.research.google.com/drive/1XA8lrc0D1K1-xWG6vVKqub9kJCDyljvZ

```
url = 'https://oceandata.sci.gsfc.nasa.gov/opendap/hyrax/MODISA/L3SMI/2009/041/A20090412009048.L3m_8D_CHL_chlor_a_4km.nc'
ds = xr.open_dataset(url)

data_mab_nj = ds.sel( lat=slice(32, 25), lon=slice(-76,-70))

powerspec = xrft.power_spectrum(data_mab_nj.chlor_a, dim=['lat', 'lon'])
iso_powerspec = xrft.isotropic_powerspectrum(data_mab_nj.chlor_a, dim=['lat', 'lon'],
                                  detrend='constant',window=False, nfactor=4,)

iso_powerspec.plot()
```

![image](https://user-images.githubusercontent.com/2497349/79510454-61add800-800b-11ea-917e-2cddf9cd7555.png)

**Comment by roxyboy** [comment]
Again, this is most likely because you are inputting negative coordinates such as the longitude, which xrft bases its wavenumber on to calculate the isotropization.

**Comment by roxyboy** [comment]
Also for the power_spectrum case, you have the density flag on as True, which uses the wavenumber spacing based on the given coordinates of the input so that is why you are getting negative values. I tried out your code but if you set the density flag to False, you should get only positive values as you would expect from the spectrum of a Chl field.

**Comment by rabernat** [comment]
Thanks @patrickcgray for reporting this issue. Whatever the explanation, this is clearly a bug: a power spectrum should never be negative.

@roxyboy - thanks for investigating and helping identify the coding details which cause this bug. Sounds like it should be an easy fix.

**Comment by roxyboy** [comment]
It's not a bug of xrft, it was never intended to take meta data not in MKI units (such as cycles per lat/lon).

**Comment by roxyboy** [comment]
@patrickcgray I will try to make a new PR to address the issues, which @rabernat found to be coming from xrft wrongly getting the coordinate spacings as negative when the coordinates are in descending order. Thanks for raising on issue on github and I'll let you know when I have a fix.

**Comment by rabernat** [comment]
Thanks @roxyboy. To summarize, I think we have identified two separate issues:

1. negative density normalization factor for descending coordinates 
2. how to handle data in lat / lon coords

1 should be easy to fix. 2 would be harder.

**Comment by roxyboy** [comment]
I think I will make `xrft` raise a warning for now when the coordinates are in lat/lon. Each user would probably want a different method in regridding the data onto equally distanced grids.

**Comment by rabernat** [comment]
> I think I will make `xrft` raise a warning for now when the coordinates are in lat/lon

:+1: but we should think carefully about how to do this. Parsing the relevant [CF conventions](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#latitude-coordinate) would be nice.

**Comment by patrickcgray** [comment]
Hi @rabernat and @roxyboy, thanks so much for the quick replies and problem solving. Changing the density flag does resolve the confusion, but if that density flag is set to false does that mean it disregards the CRS and just uses pixel counts?

I had been working with another example where I reprojected from WGS84 to Lambert azimuthal equal-area which you can see here: https://colab.research.google.com/drive/1RO4RjoO8RUC-B0oesa58BnQ2AA0ZMzxx. This uses the attached HYCOM geotif. This gave the same issue which I assume is also due to the negative coordinates even though the CRS is in meters.

Is there a specific projection I should be using or that you recommend to limit confusion? 

This is an awesome library and part of the xarray ecosystem, thanks for all the work in developing this set of tools!

[hycom_gs_img.tif.zip](https://github.com/xgcm/xrft/files/4493860/hycom_gs_img.tif.zip)

**Comment by rabernat** [comment]
> but if that density flag is set to false does that mean it disregards the CRS and just uses pixel counts?

It was never using the CRS. Xrft is completely unaware of geography, spherical coordinates, etc.

All that xrft does is to call [numpy.fft](https://docs.scipy.org/doc/numpy/reference/routines.fft.html) functions on the raw data of your dataarray, and then infer the resulting spectral coordinates from the input coordinates using [fftfreq](https://docs.scipy.org/doc/numpy/reference/generated/numpy.fft.fftfreq.html). The resulting spectral coordinates are proportional to the inverse of the spacing of the original coordinates. The code to do this is not very complicated and lives here:
https://github.com/xgcm/xrft/blob/a1e52e0a470548d3aa3ca78c6566fcfeb3996506/xrft/xrft.py#L208-L224

So if you input data as a function of longitude, the coordinates of the output are "cycles / degree longitude". The spacing of these output coordinates is used to normalize the spectra when `density=True`.

in your application, you are looking for cycles / m. But your coordinates are not measured in meters, they are measured in degress lat / lon. For a small patch of the Earth's surface, you can solve this by reprojecting your data to the plane. The best way to do this is an iteresting question. 
I would probably use an [orthographic projection](https://en.wikipedia.org/wiki/Orthographic_projection_in_cartography). However, depending on what you want to conserve under projection (areas, angles, etc.) a different projection may be better. [Pyresample](https://pyresample.readthedocs.io/en/latest/) is a good tool for these projections.

**Xrft does not do any such projection for you.** It naively operates on the raw data / coordinates as given by the user.  This is something we should probably clarify in the docs.

**Comment by roxyboy** [comment]
@patrickcgray PR #95 fixed the negative value issue you were having. Thanks for your patience :)

**Comment by patrickcgray** [comment]
Thanks @roxyboy for the update and @rabernat for the helpful comments!
