### ISSUE TITLE
Undocumented error on dimension names

### ISSUE THREAD

**Issue by ks905383** [xgcm/xrft#97]
I've been having issues running `xrft` (0.2.0) - an error of `'t' not found in array dimensions ('time', 'lat', 'lon')` appears, and I haven't been able to diagnose what's causing it. 

Here's an example. Running the following causes the error (using the attached file, which is just a `time x lat x lon` precipitation dataset):
```
ds = xr.open_dataset('test.nc')
xrft.power_spectrum(ds.pr.chunk({'lat':1,'lon':1}),dim='time',detrend='linear',window=True)
```

It doesn't seem to be related to the input options though - the same error shows up just when running `xrft.power_spectrum(ds.pr,dim='time')`. `t` is not a dimension in the dataset (and at least from the docs, it doesn't look like a dimension has to be named that either?) 

Apologize if this is not a bug and I'm just missing something (and that I haven't been able to get more info on what's causing this), but in that case it might be nice to have a specific error message for it. 

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/.conda/envs/climate1/lib/python3.7/site-packages/xarray/core/common.py in _get_axis_num(self, dim)
    172         try:
--> 173             return self.dims.index(dim)
    174         except ValueError:

ValueError: tuple.index(x): x not in tuple

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-46-44b7f9b05769> in <module>
----> 1 xrft.power_spectrum(ds.pr.chunk({'lat':1,'lon':1}),dim='time',detrend='linear',window=True)

~/.conda/envs/climate1/lib/python3.7/site-packages/xrft/xrft.py in power_spectrum(da, spacing_tol, dim, real, shift, detrend, window, chunks_to_segments, density)
    400     daft = dft(da, spacing_tol,
    401               dim=dim, real=real, shift=shift, detrend=detrend, window=window,
--> 402               chunks_to_segments=chunks_to_segments)
    403 
    404     if dim is None:

~/.conda/envs/climate1/lib/python3.7/site-packages/xrft/xrft.py in dft(da, spacing_tol, dim, real, shift, detrend, window, chunks_to_segments)
    280 
    281     # the axes along which to take ffts
--> 282     axis_num = [da.get_axis_num(d) for d in dim]
    283 
    284     N = [da.shape[n] for n in axis_num]

~/.conda/envs/climate1/lib/python3.7/site-packages/xrft/xrft.py in <listcomp>(.0)
    280 
    281     # the axes along which to take ffts
--> 282     axis_num = [da.get_axis_num(d) for d in dim]
    283 
    284     N = [da.shape[n] for n in axis_num]

~/.conda/envs/climate1/lib/python3.7/site-packages/xarray/core/common.py in get_axis_num(self, dim)
    167             return tuple(self._get_axis_num(d) for d in dim)
    168         else:
--> 169             return self._get_axis_num(dim)
    170 
    171     def _get_axis_num(self: Any, dim: Hashable) -> int:

~/.conda/envs/climate1/lib/python3.7/site-packages/xarray/core/common.py in _get_axis_num(self, dim)
    173             return self.dims.index(dim)
    174         except ValueError:
--> 175             raise ValueError(f"{dim!r} not found in array dimensions {self.dims!r}")
    176 
    177     @property

ValueError: 't' not found in array dimensions ('time', 'lat', 'lon')
```

[test.nc.zip](https://github.com/xgcm/xrft/files/4989016/test.nc.zip)

**Comment by roxyboy** [comment]
Hi @ks905383, thanks for opening an issue. Could you post here what `ds` looks like?

**Comment by dcherian** [comment]
I think you need `dim=("time",)`

**Comment by rabernat** [comment]
> I think you need `dim=("time",)`

This is really annoying! We should have fixed this long ago.

**Comment by ks905383** [comment]
Thanks for the quick answer, everyone!

Yeah, changing `dim='time'` to `dim=['time']` or `dim=('time',)` seems to get rid of this error. Thanks all! Running into a separate issue where there's a type error a few turtles down in a `isfinite` call, but let me see if I can fix that on my end.

**Comment by roxyboy** [comment]
@rabernat We should probably release a new version. I recall us fixing it but it was never linked to `conda-forge` nor `pip`.

**Comment by roxyboy** [comment]
I was referring to here: https://github.com/xgcm/xrft/blob/28f534c7e35a8d772c8c5ef7b697e3f23f413e5a/xrft/xrft.py#L308

**Comment by rabernat** [comment]
> We should probably release a new version.

Please go for it if you have the time!

**Comment by roxyboy** [comment]
An automated release would definitely be nice. I'll take a stab at it tomorrow.
