### ISSUE TITLE
CFTime vs. pd.datetime

### ISSUE THREAD

**Issue by ks905383** [xgcm/xrft#99]
Found out the type error issue I mentioned in the other thread. 

The dataset I was using has time imported `cftime` format (since it's a `noleap` calendar, which are imported as `cftime.datetime` index per `xarray` docs). 

Unfortunately, `cftime` formatted dates cause an error when `dft` is run on the `time` dimension, in the `# verify even spacing of input coordinates` section:

```
for d in dim:
        coord = da[d]
        diff = np.diff(coord)
        if pd.api.types.is_timedelta64_dtype(diff):
            # convert to seconds so we get hertz
            diff = diff.astype('timedelta64[s]').astype('f8')
        delta = diff[0]
        if not np.allclose(diff, diff[0], rtol=spacing_tol):
            raise ValueError("Can't take Fourier transform because "
                             "coodinate %s is not evenly spaced" % d)
        delta_x.append(delta)
```

Specifically, the `if` statement only converts `timedelta64` type values to integers; in my case, `diff` is kept as `datetime.timedelta`. Since `np.allclose()` requires numeric inputs, the code fails at `if not np.allclose(diff,diff[0],rtol=spacing_tol)`. 

**Dealing more generally with `noleap` calendars**
A related issue is that even converting `diff` to a supported format (using `ds.indexes['time'].to_datetimeindex()` poses a problem - 

```
/home/kschwarzwald/.conda/envs/climate1/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: Converting a CFTimeIndex with dates from a non-standard calendar, 'noleap', to a pandas.DatetimeIndex, which uses dates from the standard calendar.  This may lead to subtle errors in operations that depend on the length of time between dates.
  """Entry point for launching an IPython kernel.
```
In other words, `diff` will now have twice the value on "leap" days, which don't exist in the original dataset, and therefore trigger the "coordinate is not evenly spaced error" (and presumably cause issues with the Fourier transform).

**Proposed Solution** 
A first useful addition would probably be raising a `TypeError` on `cftime` dimensions. 

But further, I think this can be fixed by just adding something like:

```
if type(coord.values[0]) is cftime._cftime.DatetimeNoLeap:
  coord = cftime.date2num(coord,'hours since 1800-01-01 00:00:00','noleap')
```
before `diff` is called, which puts it in a numeric format that's readable by `np.allclose`. 

**Example of Error** 
```
ds = xr.open_dataset('test.nc')
xrft.power_spectrum(ds.pr,dim=['time'])
```
resulting in: 
```---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-140-86a08453bf4a> in <module>
----> 1 xrft.power_spectrum(ds2.pr,dim=['time'])

~/.conda/envs/climate1/lib/python3.7/site-packages/xrft/xrft.py in power_spectrum(da, spacing_tol, dim, real, shift, detrend, window, chunks_to_segments, density)
    400 
    401     daft = dft(da, spacing_tol,
--> 402               dim=dim, real=real, shift=shift, detrend=detrend, window=window,
    403               chunks_to_segments=chunks_to_segments)
    404 

~/.conda/envs/climate1/lib/python3.7/site-packages/xrft/xrft.py in dft(da, spacing_tol, dim, real, shift, detrend, window, chunks_to_segments)
    293             diff = diff.astype('timedelta64[s]').astype('f8')
    294         delta = diff[0]
--> 295         breakpoint()
    296         if not np.allclose(diff, diff[0], rtol=spacing_tol):
    297             raise ValueError("Can't take Fourier transform because "

<__array_function__ internals> in allclose(*args, **kwargs)

~/.conda/envs/climate1/lib/python3.7/site-packages/numpy/core/numeric.py in allclose(a, b, rtol, atol, equal_nan)
   2169 
   2170     """
-> 2171     res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
   2172     return bool(res)
   2173 

<__array_function__ internals> in isclose(*args, **kwargs)

~/.conda/envs/climate1/lib/python3.7/site-packages/numpy/core/numeric.py in isclose(a, b, rtol, atol, equal_nan)
   2267     y = array(y, dtype=dt, copy=False, subok=True)
   2268 
-> 2269     xfin = isfinite(x)
   2270     yfin = isfinite(y)
   2271     if all(xfin) and all(yfin):

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

Here's what `ds` looks like:  
<img width="618" alt="Bildschirmfoto 2020-07-28 um 10 58 19 AM" src="https://user-images.githubusercontent.com/16925278/88690225-6c2b4380-d0c9-11ea-91a1-a0513bd2f844.png">

[test.nc.zip](https://github.com/xgcm/xrft/files/4989503/test.nc.zip)

**Comment by ks905383** [comment]
`In other words, diff will now have twice the value on "leap" days, which don't exist in the original dataset, and therefore trigger the "coordinate is not evenly spaced error" (and presumably cause issues with the Fourier transform).` 
actually never mind on that last bit, it looks like the issue is *just* in determining whether the coordinates are evenly spaced, and does not affect the actual calculation

**Comment by roxyboy** [comment]
Does PR #100 seem good for you @ks905383 ??

**Comment by ks905383** [comment]
This looks excellent - thank you very much! I can also contribute adding 360-day support as well (the most annoying of calendars, but some climate models use 'em anyways).

**Comment by roxyboy** [comment]
Ok, I'll add the 360-day support.
